trigger:
- main

pool:
  vmImage: ubuntu-22.04

stages:
- stage: Build
  jobs:
  - job: BuildCDKApplication
    pool:
      vmImage: 'ubuntu-22.04'
    continueOnError: false
    steps:
      - script: |
          sudo apt install nodejs
          sudo apt install npm
          node --version
          npm --version
        displayName: 'install Node.js and NPM'
      - script: |
          npm install -g aws-cdk
          cdk --version
        displayName: 'install CDK'
      - script: |
          cd PersonalInfrastructure/
          cdk synth
        displayName: 'synth'
      - script: |
          dotnet --list-sdks
          ls -la
          cd src/
          ls -la
          dotnet test
        displayName: 'test'
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(Build.SourcesDirectory)'
          includeRootFolder: true
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/CDKApplication.zip'
          replaceExistingArchive: true
          verbose: true
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Pipeline.Workspace)'
          artifact: 'CDKApplication'
          publishLocation: 'pipeline'
- stage: Deployment
  dependsOn: Build
  jobs:
  - deployment: InfrastructureDeployment
    pool:
      vmImage: 'ubuntu-22.04'
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              sudo apt-get install awscli
              aws configure set aws_access_key_id $(AWS_ACCESS_KEY_ID)
              aws configure set aws_secret_access_key $(AWS_SECRET_ACCESS_KEY)
              aws configure set aws_default_region $(AWS_DEFAULT_REGION)
              aws --version
            displayName: 'install and configure AWS CLI'
          - script: |
              sudo apt install nodejs
              sudo apt install npm
              node --version
              npm --version
            displayName: 'install Node.js and NPM'
          - script: |
              npm install -g aws-cdk
              cdk --version
            displayName: 'install CDK'
          - script: |
              ls -la
              cd PersonalInfrastructure
              npm install
              cdk deploy
            displayName: 'install and deploy application'